Adds configurable undo history depth
platz1de/EasyEdit pull request #114
Opened 2024-03-28 20:07 UTC by elftausend

This PR adds a configurable undo history depth. Hence, steps are only remembered up to `history-depth`.

The wiki states:
```
Your selection size is mostly only limited by the space the undo-ing data needs (there currently is no option to disable undo).
```
Now, there should be an option to disable undo by setting `history-depth` to 0. (-1 for "infinite")
Hopefully, `CleanStorageTask` is doing what I hope it does. 😅

2024-03-28 22:28 UTC, platz1de requested changes
Please target `dev` branch (dev and master are currently at par)
I would also suggest using the [count-method](https://www.php.net/manual/en/spldoublylinkedlist.count.php) instead of a manual counter for the current depth

Looks good otherwise

2024-03-28 22:31 UTC, platz1de commented on resources/config.yml
> +#Maximum amount of undo/redo steps
This description should probably also mention `-1` meaning no limit

2024-03-29 07:39 UTC, elftausend commented
> I would also suggest using the [count-method](https://www.php.net/manual/en/spldoublylinkedlist.count.php) instead of a manual counter for the current depth
Thought it would make sense performance wise as this method seems to traverse the entire list. Does not really matter probably in practice

2024-03-29 22:23 UTC, platz1de approved these changes

2024-03-29 22:24 UTC, merged

2024-03-29 22:24 UTC, platz1de commented
Thank you!